#pragma once
#include <stdio.h>
#include <stdlib.h>
#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <ctype.h>
#include <limits.h>
#include <string.h>
#include <locale.h>
#include <wchar.h>

#include "Types.h"
#include "Buffer.h"
#include "Pairu.h"
#include "Dir.h"
#include "Board.h"
#include "MoveCheck.h"
#include "Print.h"
#include "Game.h"
#include "Turn.h"
